ShoppingStore/Controllers/ItemsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingStore.Models;
using ShoppingStore.Models.Dtos;
using ShoppingStore.Repository.Interfaces;
using System.Data;

namespace ShoppingStore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ItemsController : Controller
    {
        private readonly IItemsRepository _itemsService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMapper _mapper;

        public ItemsController(IItemsRepository itemsService, UserManager<IdentityUser> userManager, IMapper mapper)
        {
            _itemsService = itemsService;
            _userManager = userManager;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index([FromQuery] int page = 1, [FromQuery] int pageSize = 3, [FromQuery] string filter = "")
        {
              return View(await _itemsService.GetAllItems(page,pageSize,filter));
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _itemsService.GetItem((Guid)id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,ImageURL,DateCreated")] ItemsDto itemDto)
        {
            if (ModelState.IsValid)
            {
              var item = _mapper.Map<Items>(itemDto);
              item.Id = Guid.NewGuid();
              var result = await _itemsService.AddItem(item);
              if(item == null)
                    return NotFound();
               return RedirectToAction(nameof(Index));
            }
            return View(itemDto);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _itemsService.GetItem((Guid)id);
            if (items == null)
            {
                return NotFound();
            }
            return View(items);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description,Price,ImageURL,DateCreated")] Items items)
        {
            if (id != items.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                  var result =  await _itemsService.UpdateItem(id,items);
                  if(!result)
                        return NotFound();
               
                return RedirectToAction(nameof(Index));
            }
            return View(items);
        }

        
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _itemsService.GetItem((Guid)id);  
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
           
            var items = await _itemsService.GetItem(id);
            if (items != null)
            {
              await _itemsService.DeleteItem(id);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ShoppingStore/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using ShoppingStore.Common.Extensions;
using ShoppingStore.Models;
using ShoppingStore.Repository;
using ShoppingStore.Repository.Interfaces;
using System.Security.Claims;

namespace ShoppingStore.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderRepository _orderRepository;

        public OrdersController(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }
        [Authorize(Roles = "Administrator,Customer")]
        public async Task<IActionResult> Index()
        {
            var userId = User.IsInRole("Administrator") ? string.Empty : User.FindFirstValue(ClaimTypes.NameIdentifier); ;
            return View(await _orderRepository.GetOrdersAsync(userId));
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var orders = await _orderRepository.GetOrderAsync(id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }
        
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var order = HttpContext.Session.GetObjectFromJson<Orders>("Order");
            order.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _orderRepository.AddOrder(order, order.UserID);
            TempData["Message"] = "Order Added Successfully";
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _orderRepository.DeleteOrder(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ShoppingStore/Views/Shared/OrderPlaced.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

ShoppingStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShoppingStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color:#032830">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end ">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Items" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                       
                       
                    </ul>

                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 ">
                      

                        <div class="col">
                            <partial name="_LoginPartial" />
                        </div>
                   </div>
                </div>
                
            </div>
           
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ShoppingStore 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>